description: Arbitrary task distribution platform.
homepage: http://queueflex.com
vendor: Ben Langfeld <http://langfeld.me>
maintainer: Ben Langfeld <http://langfeld.me>
license: Apache 2.0
changelog: CHANGELOG.md
targets:
  ubuntu-14.04:
  debian-8:
before:
  - echo "runtime_path=/opt/queueflex" > elixir_buildpack.config
after:
  - rm -rf .git
  - mkdir -p ../../home/queueflex
  - "cp -R /home/pkgr/{.npm,.mix,.hex} ../../home/queueflex"
buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
after_install: "packaging/postinstall.sh"
